\input texinfo   @c -*-texinfo-*-
@c %**start of header

@setfilename fomus.info
@include version.texi
@settitle FOMUS Documentation
@c %**end of header

@copying
This manual is for FOMUS @value{VERSION}.
Copyright @copyright{} 2009, 2010, 2011 David Psenicka.  All Rights Reserved.

@quotation
Permission is granted to copy, distribute and/or modify this
document under the terms of the GNU Free Documentation License,
Version 1.3 or any later version published by the Free Software
Foundation; with no Invariant Sections, no Front-Cover Texts and
no Back-Cover Texts.  A copy of the license is included in the
section entitled ``GNU Free Documentation License.''
@end quotation
@end copying
     
@titlepage
@title FOMUS Documentation
@c @subtitle subtitle-if-any
@c @subtitle second-subtitle
@author David Psenicka
     
@page
@vskip 0pt plus 1filll
@insertcopying
     
@end titlepage
     
@ifnottex
@node Top, Introduction, (dir), (dir)
@top FOMUS Documentation
     
This manual is for FOMUS @value{VERSION}.
@end ifnottex

@menu
* Introduction::                
* Installing::                  
* Usage::                       
* Tutorial::                    
* Reference::                   
* `.fms' File Examples::        
* Lisp Examples::               
* SAL Examples::                
* MIDI Import Examples::        
* Sample Scores::               
* Sample Module Code::          
* Examples Index::              
@end menu

@contents
     
@defcodeindex ex

@macro fomusex{capt, cprfx, prfx, sffx, num}
@float Figure,fig\cprfx\\num\
@multitable @columnfractions 0.3 0.3
@item 
@smallformat
@verbatiminclude \prfx\\num\.\sffx\
@end smallformat
@tab
@image{\prfx\\num\,,,,png}
@end multitable
@caption{\capt\}
@end float
@end macro

@macro ccmoduleex{file, prfx}
@float Figure,mod\file\
@smallformat
@verbatiminclude \file\.\prfx\
@end smallformat
@caption{\file\.\prfx\}
@end float
@end macro

@macro exref{str}
@ifset fileexs
@ref{\str\ (File)} 
@end ifset
@ifset lispexs
@ref{\str\ (Lisp)} 
@end ifset
@ifset salexs
@ref{\str\ (SAL)} 
@end ifset
@end macro

@include intro.texi

@include install.texi

@include usage.texi

@include tutorial.texi

@include reference.texi
 

@include file_examples.texi

@include lisp_examples.texi

@include sal_examples.texi

@include midi_examples.texi

@include scores.texi

@include exmods.texi


@include exs_index.texi

@c @ref
@c @xref = ``See ...''
@c @pxref = ``see ...''

@c to update all docs, nodes, etc.:
@c make update

@bye
