@node Sample Module Code, Examples Index, Sample Scores, Top
@chapter Sample Module Code

The following C++ files show the code for several of FOMUS's modules.
The module API is still unstable and subject to change before the software's initial release.

@menu
* untie.cc::                    
@end menu

@node untie.cc,  , Sample Module Code, Sample Module Code
@section untie.cc

@ccmoduleex{untie, cc}
