@node MIDI Import Examples, Sample Scores, SAL Examples, Top
@chapter MIDI Import Examples

@menu
* Some Basic MIDI Examples::    
@end menu

@node Some Basic MIDI Examples,  , MIDI Import Examples, MIDI Import Examples
@section Some Basic MIDI Examples

@subsection Tracks to Voices

MIDI files can be imported into FOMUS with a little help.  For best results, 
open the MIDI file in a sequencer and examine at how the tracks are organized and how time values should be scaled.
Then setup a @file{.fms} file to act as a ``header file'' for the MIDI file.
The header file should contain a few global settings and parts with instruments that include import definition objects.
The import objects should contain the necessary information for importing the midi data.

This first example uses a MIDI file taken from Alan U. Kennington's collection of WTC MIDI files at @uref{http://www.topology.org/midi/wtk/}.

@fomusex{Bach, Mid, mid, fms, 001}

An instrument is defined based on the build-in piano instrument with three import objects, one to match each of the three tracks in the MIDI file.
Incoming MIDI from track 1 is sent to the part with voice 1.  Track 2 data is set to voice 2, etc..  
