@node Sample Scores, Sample Module Code, MIDI Import Examples, Top
@chapter Sample Scores

This collection of sample @file{.fms} files also serve as ``real world'' tests of FOMUS's features.  
Each score is chosen to exercise FOMUS in a different way and used to fine tune its decision-making.
Most of the @file{.fms} files contain only time, duration and pitch information with score marks (voices or voice hints are specified in some of them).  
The intention is that FOMUS should do a reasonable job notating these but not necessarily reproduce the original scores exactly
(a difficult task with FOMUS's current set of general-purpose algorithms).
More scores will be added and the current ones should improve as FOMUS's features are further refined.

All of the images were produced by LilyPond.
(Each @file{.fms} file was used to produce a @file{.ly} file, which was then processed by LilyPond to produce the image shown.)

@menu
* WTC::                         
* Saudade::                     
@end menu

@node WTC, Saudade, Sample Scores, Sample Scores
@section WTC

@fomusex{Bach, Sc, score, fms, 001}

@node Saudade,  , WTC, Sample Scores
@section Saudade

@fomusex{Milhaud, Sc, score, fms, 002}
